language:
  - objective-c

env:
  matrix:
    - VERSION=2.7.7 PACKAGES="numpy"

install:
  - set -vx  # echo commands
  - source travis_install.sh

script:
  - echo $PWD
  - mkdir tmp_test_dir
  - cd tmp_test_dir
  - source ../travis_test.sh
  - cd ..

after_failure:
  - echo $PWD

before_deploy: cd build/wheelhouse
deploy:
  provider: cloudfiles
  username: travis-worker
  api_key:
    secure: U+rKEiR6sQ+vsTJt3MuqqZwWvPV4gkjnQvzeR6cP9JZpfvkKuaa+vcgj7OngZ69DUgFTzRiTnFAxCbArGpDUkbP9V+kX5UgkePMdxhK+j9V0UOo8g+QwZtlqmV78pTXemWndwbqcy0uyfxuBpxhPXGSAHuzk+pZUbhH2zSEfh0s=
  region: ORD
  container: wheels
  skip_cleanup: true
