language:
  - objective-c

env:
  matrix:
    - PY_VERSION=2.7.7 PACKAGES=numpy
    - PY_VERSION=2.7.7 PACKAGES=scipy
    - PY_VERSION=3.3.5 PACKAGES=numpy
    - PY_VERSION=3.3.5 PACKAGES=scipy
    - PY_VERSION=3.4.1 PACKAGES=numpy
    - PY_VERSION=3.4.1 PACKAGES=scipy

install:
  - set -vx  # echo commands
  - source ./testing/install.sh

script:
  - echo $PWD
  - mkdir tmp_test_dir
  - cd tmp_test_dir
  - source ../testing/test.sh

after_failure:
  - echo $PWD
