language:
  - objective-c

env:
  global:
    - NP_TAG=v1.8.2
    - SP_TAG=v0.10.0
  matrix:
    - VERSION=2.7.7 PACKAGES="numpy"
    - VERSION=3.3.5 PACKAGES="numpy"
    - VERSION=3.4.1 PACKAGES="numpy"
    #- VERSION=2.7.7 PACKAGES="scipy"
    # - VERSION=3.3.5 PACKAGES="scipy"
    # Tests fail for np 1.7.1 / Python 3.4, so upgrade numpy to current pip
    # - VERSION=3.4.1 UPGRADE_NP=1 PACKAGES="scipy"

install:
  - set -vx  # echo commands
  - source travis_install.sh

script:
  # delete installed compiler to test on clang-only system
  - sudo rm -rf /usr/local/gfortran
  - echo $PWD
  - mkdir tmp_test_dir
  - cd tmp_test_dir
  - source ../travis_test.sh
  - cd ..

after_failure:
  - echo $PWD

before_deploy: cd build/wheelhouse
deploy:
  provider: cloudfiles
  username: travis-worker
  api_key:
    secure: "DdFsbTyikWMjSP4ZyGx/iKziDMSlnWDU/tAtDXrx2LrMxhBRmwAt8gdhwgoaEcmQ7XJ9ae5L5d8Aiy/q+Ob3w3VSjrFATXQnnry650PfTCrzrbqGO+pbj49LiVYLNEXsDB76veXUXAvnH10/Iii4EhO8r7c8rPNIAtOMIeZFffI="
  region: ORD
  container: wheels
  skip_cleanup: true
