language:
  - objective-c

env:
  global:
    - NP_TAG=v1.9.0b2
    - SP_TAG=v0.14.1
  matrix:
    - VERSION=2.7.7 PACKAGES="numpy"
    - VERSION=3.3.5 PACKAGES="numpy"
    - VERSION=3.4.1 PACKAGES="numpy"
    #- VERSION=2.7.7 PACKAGES="scipy"
    #- VERSION=3.3.5 PACKAGES="scipy"
    ## Tests fail for np 1.7.1 / Python 3.4, so upgrade numpy to current pip
    #- VERSION=3.4.1 UPGRADE_NP=1 PACKAGES="scipy"

install:
  - set -vx  # echo commands
  - source travis_install.sh

script:
  # delete installed compiler to test on clang-only system
  - sudo rm -rf /usr/local/gfortran
  - echo $PWD
  - mkdir tmp_test_dir
  - cd tmp_test_dir
  - source ../travis_test.sh
  - cd ..

after_failure:
  - echo $PWD

before_deploy: cd build/wheelhouse
deploy:
  provider: cloudfiles
  username: travis-worker
  api_key:
    secure: U+rKEiR6sQ+vsTJt3MuqqZwWvPV4gkjnQvzeR6cP9JZpfvkKuaa+vcgj7OngZ69DUgFTzRiTnFAxCbArGpDUkbP9V+kX5UgkePMdxhK+j9V0UOo8g+QwZtlqmV78pTXemWndwbqcy0uyfxuBpxhPXGSAHuzk+pZUbhH2zSEfh0s=
  region: ORD
  container: wheels
  skip_cleanup: true
