  /* This file generated by /Users/mb312/atlas/atlas-3.10.1//tune/threads/probe_nthr.c */
#ifndef ATLAS_NTHREADS_H
   #define ATLAS_NTHREADS_H

#include "pthread.h"
   #define ATL_NTHREADS 4
   #define ATL_NTHRPOW2 2
   #ifdef ATL_LAUNCHORDER
       static int ATL_launchorder[4] = {0,2,1,3};
   #endif

#endif
