#ifndef ATL_INSTINFO_H
   #define ATL_INSTINFO_H

#define ATL_ARCH "UNKNOWNx8632SSE2"
#define ATL_INSTFLAGS "-1 0 -a 1 -l 1"
#define ATL_F2CDEFS "-DAdd_ -DF77_INTEGER=int -DStringSunStyle"
#define ATL_ARCHDEFS "-DATL_OS_OSX -DATL_ARCH_UNKNOWNx86 -DATL_CPUMHZ=1300 -DATL_SSE2 -DATL_SSE1 -DATL_GAS_x8632"
#define ATL_DKCFLAGS "-O -fomit-frame-pointer -msse2 -mfpmath=sse -msse2 -m32 -m32"
#define ATL_DKC "/usr/local/gfortran/bin/gcc"
#define ATL_SKCFLAGS "-O -fomit-frame-pointer -msse2 -mfpmath=sse -msse2 -m32 -m32"
#define ATL_SKC "/usr/local/gfortran/bin/gcc"
#define ATL_DMCFLAGS "-O -fomit-frame-pointer -msse2 -mfpmath=sse -msse2 -m32 -m32"
#define ATL_DMC "/usr/local/gfortran/bin/gcc"
#define ATL_SMCFLAGS "-O -fomit-frame-pointer -msse2 -mfpmath=sse -msse2 -m32 -m32"
#define ATL_SMC "/usr/local/gfortran/bin/gcc"
#define ATL_ICCFLAGS "-DL2SIZE=4194304 -I/Users/mb312/atlas/atlas-3.10.1-build-32-sse2-full-gcc4.8.2/include -I/Users/mb312/atlas/atlas-3.10.1//include -I/Users/mb312/atlas/atlas-3.10.1//include/contrib -DAdd_ -DF77_INTEGER=int -DStringSunStyle -DATL_OS_OSX -DATL_ARCH_UNKNOWNx86 -DATL_CPUMHZ=1300 -DATL_SSE2 -DATL_SSE1 -DATL_GAS_x8632 -m32 -DATL_FULL_LAPACK -DATL_NCPU=4 -O -fomit-frame-pointer -msse2 -mfpmath=sse -msse2 -m32 -m32"
#define ATL_ICC "/usr/local/gfortran/bin/gcc"
#define ATL_F77FLAGS "-O -msse2 -mfpmath=sse -msse2 -m32 -m32"
#define ATL_F77 "/usr/local/gfortran/bin/gfortran"
#define ATL_DKCVERS "gcc (GCC) 4.8.2"
#define ATL_SKCVERS "gcc (GCC) 4.8.2"
#define ATL_DMCVERS "gcc (GCC) 4.8.2"
#define ATL_SMCVERS "gcc (GCC) 4.8.2"
#define ATL_ICCVERS "gcc (GCC) 4.8.2"
#define ATL_F77VERS "GNU Fortran (GCC) 4.8.2"
#define ATL_SYSINFO "Darwin shanghai.local 13.2.0 Darwin Kernel Version 13.2.0: Thu Apr 17 23:03:13 PDT 2014; root:xnu-2422.100.13 1/RELEASE_X86_64 x86_64"
#define ATL_DATE    "Fri Jun  6 11:59:42 PDT 2014"
#define ATL_UNAM    "mb312"
#define ATL_VERS    "3.10.1"

#endif
