/* Generated by /Users/mb312/atlas/atlas-3.10.1//CONFIG/src/probe_aff.c */
#ifndef ATL_TAFFINITY_H
   #define ATL_TAFFINITY_H

#define ATL_HAS_AFFINITY 0
#define ATL_PAFF_NONE 1
#define ATL_NOAFFINITY 1

#endif /* end multiple inclusion guard */
